
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
services:
  app:
    container_name: point_cloud_change_detection
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    runtime: nvidia
Why did you want only sex with me?

Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.

Actually, you want me only for sex friend, you never really love me. when you told me "love me" you lie always.
